language: ruby
sudo: false

before_install: gem update --system

rvm:
  - 2.2.2
  - 2.3.0

gemfile:
  - Gemfile

script:
  - bundle exec rspec
  - bundle exec rubocop --display-cop-names

sudo: false
